{
 "title": "FullNodes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "owner", "label": "Owner", "query": "label_values(owner)" }
  ]
 },
 "panels": [
  { "title": "State Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State Sync Lag",
   "type": "graph",
   "description": "Ledger timestamp's lag compared to the nodes current time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(aptos_state_sync_timestamp{type=\"real\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"} - on(owner, kubernetes_pod_name) aptos_state_sync_timestamp{type=\"synced\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"})",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Synchronized",
   "type": "graph",
   "description": "1 = It's fully synchronized\n0 = It's NOT synchronized",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(aptos_state_sync_version{type=\"highest\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"} - on(owner, kubernetes_pod_name) aptos_state_sync_version{type=\"committed\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"}) < bool 15",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "State Sync Rate",
   "type": "graph",
   "description": "Rate at which the synced version is increasing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_version{type=\"synced\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "State Sync Upstream Peers",
   "type": "graph",
   "description": "Number of upstream peers that can provide up to date information about the ledger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aptos_state_sync_active_upstream_peers{kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"}) by (kubernetes_pod_name, owner) ",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Mempool Pending transactions",
   "type": "graph",
   "description": "Number of uncommitted but still valid (not expired nor discarded) transactions in the nodes Mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{index=\"system_ttl\", kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Mempool Txn Commit Latency",
   "type": "graph",
   "description": "The time between Mempool receiving the transaction and time to be committed. Note: due to reliability mechanisms, this value can be lower than it really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aptos_core_mempool_txn_commit_latency_sum{kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"} / aptos_core_mempool_txn_commit_latency_count{kubernetes_pod_name=~\".*fullnode.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Connections (Incoming)",
   "type": "graph",
   "description": "Number of Inbound Connections as measured by AptosNet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner,kubernetes_pod_name)(aptos_connections{direction=\"inbound\",network_id=\"Public\", owner=~\"$owner\"})",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Connections (Outgoing)",
   "type": "graph",
   "description": "Number of  Outbound Network Connections as measured by AptosNet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, kubernetes_pod_name)(aptos_connections{direction=\"outbound\",network_id=\"Public\", owner=~\"$owner\"})",
     "legendFormat": "{{owner}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*fullnode.*\", owner=~\"$owner\"}[$interval])) by (owner, pod)",
     "legendFormat": "{{owner}}-{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\".*fullnode.*\", owner=~\"$owner\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\".*fullnode.*\", owner=~\"$owner\"}[$interval])) by (owner, pod)",
     "legendFormat": "{{owner}}-{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\".*fullnode.*\", owner=~\"$owner\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Percentage Disk Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\".*fullnode.*\", owner=~\"$owner\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*fullnode.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"fullnode\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\".*fullnode.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{pod}}-memory-limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"fullnode\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"fullnode\", owner=~\"$owner\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}